.TH OOKBRICKS 3 2013-10-03 "" "Ook Programmer's Manual"
.SH NAME
ookbricks \- reports the total number of bricks in a dataset
.SH SYNOPSIS
.nf
.B #include <ook.h>
.sp
.BI "size_t ookbricks(const struct ookfile* " of );
.fi

.SH DESCRIPTION
.LP
.BR ookbricks ()
reports the total number of bricks in a dataset.  This is a simple calculation
based on the total number of voxels and the brick size, but this is provided
for convenience nonetheless.

.SH "RETURN VALUE"
.BR ookbricks ()
returns the total number of bricks in a dataset.

.SH ERRORS
.TP
.B EINVAL
The given
.IR of
pointer does not point to a valid
.I struct\ ookfile
.

.SH "SEE ALSO"

.BR ookread (3),
.BR ookcreate (3)
